version: '3'
services:
  app:
    build: .
    depends_on:
      - MySQL
    environment:
      DB_USER: root
      DB_PASSWORD: vLWABIdIsyImdWEqBhXOHefpSDfbudRy
      DB_HOST: mysql.railway.internal
      DB_PORT: 3306
      DB_NAME: railway
      DB_URL: mysql+mysqldb://root:vLWABIdIsyImdWEqBhXOHefpSDfbudRy@junction.proxy.rlwy.net:50075/railway
    command: ["./wait-for-it.sh", "meinsql", "3306", "--", "python3", "-m", "api.v2.app"]