version: '3'
services:
  app:
    image: your-app-image
    environment:
      - MYSQL_HOST=mysql.railway.internal
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=railway
      - MYSQL_USER=root
      - MYSQL_PASSWORD=vLWABIdIsyImdWEqBhXOHefpSDfbudRy
      - DATABASE_URL=mysql://root:vLWABIdIsyImdWEqBhXOHefpSDfbudRy@mysql.railway.internal:3306/
    ports:
      - "5000:5000"  # Assuming your app runs on port 5000
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://root:vLWABIdIsyImdWEqBhXOHefpSDfbudRy@mysql.railway.internal:3306/
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
