"""Switch from user_tags table to UserTag model

Revision ID: 014457e05b73
Revises: af570c7625e0
Create Date: 2024-09-12 13:52:30.806058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014457e05b73'
down_revision: Union[str, None] = 'af570c7625e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
