"""Switch from user_tags table to UserTag model

Revision ID: 04a323f23b9f
Revises: f4d1ca10afc3
Create Date: 2024-09-12 13:42:52.310380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a323f23b9f'
down_revision: Union[str, None] = 'f4d1ca10afc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tags', sa.Column('id', sa.String(length=36), nullable=False))
    op.add_column('user_tags', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_tags', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tags', 'updated_at')
    op.drop_column('user_tags', 'created_at')
    op.drop_column('user_tags', 'id')
    # ### end Alembic commands ###
