"""revised tag name uniqueness

Revision ID: a80d49a3dfcb
Revises: 91a2efe8c839
Create Date: 2024-09-10 19:23:43.974362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80d49a3dfcb'
down_revision: Union[str, None] = '91a2efe8c839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'tags', ['name'], unique=True)
    # ### end Alembic commands ###
