"""Switch from user_tags table to UserTag model

Revision ID: af570c7625e0
Revises: 04a323f23b9f
Create Date: 2024-09-12 13:49:34.262953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af570c7625e0'
down_revision: Union[str, None] = '04a323f23b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
